### ISSUE TITLE
Database Parameters don't agree with plots

### ISSUE THREAD

**Issue by aabills** [junzis/wrap#1]
Hello,

I think this is quite a useful database, and I want to use the distributions for some monte carlo sampling for aircraft performance parameters. However, some of the database parameters don't seem to agree with the plots. For example, the shape parameter for cruise range for the A320 is listed as 1, which does not agree well with the shape of the plot provided. Do you think you could update the parameters with the proper values? 

Thanks!

**Comment by junzis** [comment]
You are right. The precisions for some of the parameters are too low. In this case, it should be 1.7 instead of 1. So I updated all the tables. This should be fixed with 563ea8a now.

**Comment by aabills** [comment]
Great. Thanks!
